use crate::config::Config;
use crate::models::app::{
    App, DatabaseConfig, NetworkMode, PortProtocol, Service,
};
use crate::models::compose::*;
use anyhow::Context;
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use crate::constants::*;

/// 生成整个应用的目录结构和文件
pub fn generate_app(app: &App, config: &Config) -> anyhow::Result<()> {
    // 1. 创建目录
    create_directories(app, config)?;

    // 2. 生成 .env 和 .env.example
    let env_content = generate_env(app, config, false)?;
    let env_example = generate_env(app, config, true)?;
    fs::write(app.path.join(ENV_FILE), env_content)
        .context("无法写入 .env 文件")?;
    fs::write(app.path.join(ENV_EXAMPLE_FILE), env_example)
        .context("无法写入 .env.example 文件")?;

    // 3. 生成 .gitignore
    let gitignore = generate_gitignore();
    fs::write(app.path.join(GITIGNORE_FILE), gitignore)
        .context("无法写入 .gitignore 文件")?;

    // 4. 生成 README.md
    let readme = generate_readme(app, config)?;
    fs::write(app.path.join(README_FILE), readme)
        .context("无法写入 README.md 文件")?;

    // 5. 生成 docker-compose.yml
    let compose = build_compose(app, config)?;
    let yaml = serde_yaml::to_string(&compose).context("序列化 docker-compose.yml 失败")?;
    // 添加注释头部
    let header = format!(
        "# {} - {}\n# Generated by homespace\n\n",
        app.name, app.description
    );
    fs::write(app.path.join(COMPOSE_FILE), format!("{}{}", header, yaml))
        .context("无法写入 docker-compose.yml 文件")?;

    Ok(())
}

/// 创建应用的目录结构（config、data 等）
fn create_directories(app: &App, config: &Config) -> anyhow::Result<()> {
    fs::create_dir_all(&app.path)
        .with_context(|| format!("无法创建应用目录: {}", app.path.display()))?;

    // 创建 config 目录（如果有配置文件挂载）
    let has_config_mount = app.services.iter().any(|s| {
        s.volumes
            .iter()
            .any(|v| v.host_path.starts_with("./config/"))
    });
    if has_config_mount {
        fs::create_dir_all(app.path.join("config")).ok();
    }

    // 创建 data 目录
    let data_base = app.data_root.as_ref().unwrap_or(&config.paths.data_root);
    for svc in &app.services {
        let data_dir = if data_base.is_relative() {
            app.path.join(data_base).join(&app.name).join(&svc.name)
        } else {
            data_base.join(&app.name).join(&svc.name)
        };
        fs::create_dir_all(&data_dir).with_context(|| {
            format!("无法创建数据目录: {}", data_dir.display())
        })?;
        // 写入 .gitkeep
        fs::write(data_dir.join(".gitkeep"), "").ok();
    }

    Ok(())
}

/// 生成 .env / .env.example 文件内容
fn generate_env(app: &App, config: &Config, _example: bool) -> anyhow::Result<String> {
    let password_placeholder = "change-me";
    let mut buf = String::new();

    buf.push_str("# ====== 应用基本信息 ======\n");
    buf.push_str(&format!("APP_NAME={}\n", app.name));
    buf.push_str(&format!("APP_DESCRIPTION={}\n", app.description));
    buf.push('\n');

    buf.push_str("# ====== DNS / TLS ======\n");
    buf.push_str(&format!("DNS_MAIN={}\n", config.home.domain));
    buf.push_str(&format!("DNS_LIST=*.{}\n", config.home.domain));
    buf.push('\n');

    for svc in &app.services {
        buf.push_str(&format!("# ====== 服务: {} ======\n", svc.name));
        let var_prefix = svc.name.to_uppercase().replace('-', "_");

        buf.push_str(&format!("{}_IMAGE={}\n", var_prefix, svc.image));
        buf.push_str(&format!("{}_VERSION={}\n", var_prefix, svc.version));

        if !svc.internal_ports.is_empty() {
            let ports_str = svc
                .internal_ports
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<_>>()
                .join(",");
            buf.push_str(&format!("{}_PORT={}\n", var_prefix, ports_str));
        }

        // 数据库连接信息
        match &svc.database {
            DatabaseConfig::SharedPostgres {
                db_name, user, ..
            } => {
                buf.push_str(&format!("{}_POSTGRES_HOST=postgres\n", var_prefix));
                buf.push_str(&format!("{}_POSTGRES_PORT=5432\n", var_prefix));
                buf.push_str(&format!("{}_POSTGRES_USER={}\n", var_prefix, user));
                buf.push_str(&format!(
                    "{}_POSTGRES_PASSWORD={}\n",
                    var_prefix, password_placeholder
                ));
                buf.push_str(&format!("{}_POSTGRES_DB={}\n", var_prefix, db_name));
            }
            DatabaseConfig::None => {}
        }

        // 服务级环境变量
        for (key, value) in &svc.env_vars {
            let k = format!("{}_{}", var_prefix, key);
            buf.push_str(&format!("{}={}\n", k, value));
        }

        buf.push('\n');
    }

    Ok(buf)
}

/// 生成 .gitignore 文件内容
fn generate_gitignore() -> String {
    "# homespace generated\n.env\ndata/\n*.log\n".to_string()
}

/// 生成 README.md 文件内容
fn generate_readme(app: &App, _config: &Config) -> anyhow::Result<String> {
    let mut buf = String::new();
    buf.push_str(&format!("# {}\n\n", app.name));
    if !app.description.is_empty() {
        buf.push_str(&format!("{}\n\n", app.description));
    }

    buf.push_str("## 服务列表\n\n");
    buf.push_str("| Service | Image | Port | Routes | Database |\n");
    buf.push_str("|---------|-------|------|--------|----------|\n");

    for svc in &app.services {
        let ports = svc
            .internal_ports
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        let routes = svc
            .routes
            .iter()
            .map(|r| r.subdomain.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let db = match &svc.database {
            DatabaseConfig::None => "-".to_string(),
            DatabaseConfig::SharedPostgres { .. } => "infra PG".to_string(),
        };

        buf.push_str(&format!(
            "| {} | {}:{} | {} | {} | {} |\n",
            svc.name, svc.image, svc.version, ports, routes, db
        ));
    }

    buf.push_str("\n## 访问地址\n\n");
    for svc in &app.services {
        for route in &svc.routes {
            buf.push_str(&format!(
                "- https://{}{}\n",
                route.subdomain,
                route
                    .path_prefix.as_deref()
                    .unwrap_or("")
            ));
        }
    }

    if !app.services.iter().all(|s| s.routes.is_empty()) {
        buf.push_str("\n## 启动\n\n");
        buf.push_str("```bash\n");
        buf.push_str(&format!("cd {}\n", app.path.display()));
        buf.push_str("docker compose up -d\n");
        buf.push_str("```\n");
    }

    Ok(buf)
}

/// 程序化构建 `DockerCompose` 结构
fn build_compose(app: &App, config: &Config) -> anyhow::Result<DockerCompose> {
    let mut services: BTreeMap<String, ComposeService> = BTreeMap::new();
    let mut networks: BTreeMap<String, ComposeNetwork> = BTreeMap::new();
    let data_base = app.data_root.as_ref().unwrap_or(&config.paths.data_root);

    for svc in &app.services {
        let compose_svc = build_service(svc, app, config, data_base);
        services.insert(svc.name.clone(), compose_svc);

        // 收集外部网络
        if let NetworkMode::External(name) = &svc.network_mode {
            networks.entry(name.clone()).or_insert(ComposeNetwork {
                external: Some(true),
                name: Some(name.clone()),
                driver: None,
            });
        }
    }

    Ok(DockerCompose {
        version: Some("3.8".to_string()),
        services,
        networks,
        volumes: BTreeMap::new(),
    })
}

/// 构建单个服务的 `ComposeService` 定义
fn build_service(
    svc: &Service,
    app: &App,
    config: &Config,
    data_base: &Path,
) -> ComposeService {
    let var_prefix = svc.name.to_uppercase().replace('-', "_");

    // 容器名
    let container_name = if app.name == "infra" {
        svc.name.clone()
    } else {
        format!("{}-{}", app.name, svc.name)
    };

    // 网络配置
    let (network_mode, networks) = build_network_config(svc, app);

    // 端口映射
    let ports = if !svc.port_mappings.is_empty() {
        Some(
            svc.port_mappings
                .iter()
                .map(|pm| {
                    let proto = match pm.protocol {
                        PortProtocol::Tcp => "",  // 默认 tcp，不需要后缀
                        PortProtocol::Udp => "/udp",
                    };
                    format!("{}:{}{}", pm.host_port, pm.container_port, proto)
                })
                .collect(),
        )
    } else if svc.routes.is_empty()
        && !matches!(svc.network_mode, NetworkMode::Host)
        && !svc.internal_ports.is_empty()
    {
        // 没有 Traefik 路由也没有端口映射时，自动暴露第一个端口
        Some(
            svc.internal_ports
                .iter()
                .map(|p| format!("{}:{}", p, p))
                .collect(),
        )
    } else {
        None
    };

    // Traefik 标签
    let labels = build_traefik_labels(svc, app, config);

    // 卷
    let volumes = build_volumes(svc, app, data_base);

    // 环境变量（包含数据库连接）
    let environment = build_environment(svc, &var_prefix);

    // 健康检查
    let healthcheck = build_healthcheck(svc);

    ComposeService {
        image: Some(format!("${{{}_IMAGE}}:${{{}_VERSION}}", var_prefix, var_prefix)),
        container_name: Some(container_name),
        command: svc.command.clone(),
        restart: Some("unless-stopped".to_string()),
        network_mode,
        networks,
        ports,
        volumes: Some(volumes),
        environment,
        env_file: None,
        labels: Some(labels),
        depends_on: None,
        healthcheck,
        user: None,
        logging: Some(ComposeLogging::json_file("10m")),
    }
}

/// 构建网络配置（host/bridge/external）
fn build_network_config(
    svc: &Service,
    _app: &App,
) -> (Option<String>, Option<BTreeMap<String, ComposeServiceNetwork>>) {
    match &svc.network_mode {
        NetworkMode::Host => (Some("host".to_string()), None),
        NetworkMode::Bridge => {
            let mut nets = BTreeMap::new();
            // 需要 infra PostgreSQL 网络
            if matches!(svc.database, DatabaseConfig::SharedPostgres { .. }) {
                nets.insert(
                    NETWORK_POSTGRES.to_string(),
                    ComposeServiceNetwork { aliases: None },
                );
            }
            // 需要 Traefik 网络
            if !svc.routes.is_empty() {
                nets.insert(
                    NETWORK_TRAEFIK.to_string(),
                    ComposeServiceNetwork { aliases: None },
                );
            }
            if nets.is_empty() {
                (None, None)
            } else {
                (None, Some(nets))
            }
        }
        NetworkMode::External(name) => {
            let mut nets = BTreeMap::new();
            nets.insert(name.clone(), ComposeServiceNetwork { aliases: None });
            // 同时也连接 traefik（如果需要路由）
            if !svc.routes.is_empty() && name != NETWORK_TRAEFIK {
                nets.insert(
                    NETWORK_TRAEFIK.to_string(),
                    ComposeServiceNetwork { aliases: None },
                );
            }
            if matches!(svc.database, DatabaseConfig::SharedPostgres { .. })
                && name != NETWORK_POSTGRES
            {
                nets.insert(
                    NETWORK_POSTGRES.to_string(),
                    ComposeServiceNetwork { aliases: None },
                );
            }
            (None, Some(nets))
        }
    }
}

/// 构建 Traefik 路由标签
fn build_traefik_labels(svc: &Service, app: &App, config: &Config) -> Vec<String> {
    let mut labels = Vec::new();

    // 全局 Traefik 开关
    if svc.routes.is_empty() {
        return labels;
    }

    labels.push("traefik.enable=true".to_string());

    for (i, route) in svc.routes.iter().enumerate() {
        let router_name = if svc.routes.len() == 1 {
            format!("{}-{}", app.name, svc.name)
        } else {
            format!("{}-{}-{}", app.name, svc.name, i)
        };

        // 构建路由规则
        let rule = if let Some(ref path) = route.path_prefix {
            format!(
                "Host(`{}`) && PathPrefix(`{}`)",
                route.subdomain, path
            )
        } else {
            format!("Host(`{}`)", route.subdomain)
        };

        labels.push(format!(
            "traefik.http.routers.{}.rule={}",
            router_name, rule
        ));
        labels.push(format!(
            "traefik.http.routers.{}.entrypoints=websecure",
            router_name
        ));

        // TLS 始终启用
        labels.push(format!(
            "traefik.http.routers.{}.tls=true",
            router_name
        ));
        labels.push(format!(
            "traefik.http.routers.{}.tls.certresolver=cloudflare",
            router_name
        ));
        labels.push(format!(
            "traefik.http.routers.{}.tls.domains[0].main={}",
            router_name, config.home.domain
        ));
        labels.push(format!(
            "traefik.http.routers.{}.tls.domains[0].sans=*.{}",
            router_name, config.home.domain
        ));

        // 文件中间件
        if !svc.middlewares.is_empty() {
            let middleware_chain = svc
                .middlewares
                .iter()
                .map(|m| m.label_ref())
                .collect::<Vec<_>>()
                .join(",");
            labels.push(format!(
                "traefik.http.routers.{}.middlewares={}",
                router_name, middleware_chain
            ));
        }

        // service 负载均衡
        if !svc.internal_ports.is_empty() {
            labels.push(format!(
                "traefik.http.services.{}.loadbalancer.server.port={}",
                router_name,
                svc.internal_ports[0]
            ));
        }
    }

    labels
}

/// 构建卷挂载列表（时区、自定义卷、共享资源、数据卷）
fn build_volumes(svc: &Service, app: &App, data_base: &Path) -> Vec<String> {
    let mut vols: Vec<String> = Vec::new();

    // 时区映射（系统卷）
    vols.push("/etc/localtime:/etc/localtime:ro".to_string());
    vols.push("/etc/timezone:/etc/timezone:ro".to_string());

    // 自定义卷
    for vol in &svc.volumes {
        vols.push(format!(
            "{}:{}{}",
            vol.host_path,
            vol.container_path,
            if vol.read_only { ":ro" } else { "" }
        ));
    }

    // 共享资源挂载
    for mount in &svc.shared_mounts {
        // 宿主机路径需要在生成时查找 SharedResource
        vols.push(format!(
            "{{SHARED_RESOURCE_PATH:{}}}:{}{}",
            mount.resource_name,
            mount.container_path,
            if mount.read_only { ":ro" } else { "" }
        ));
    }

    // 数据卷
    let data_dir = if data_base.is_relative() {
        app.path.join(data_base).join(&app.name).join(&svc.name)
    } else {
        data_base.join(&app.name).join(&svc.name)
    };
    vols.push(format!("{}:/data", data_dir.display()));

    vols
}

/// 构建环境变量列表（数据库连接 + 自定义变量）
fn build_environment(svc: &Service, var_prefix: &str) -> Option<Vec<String>> {
    let mut envs: Vec<String> = Vec::new();

    match &svc.database {
        DatabaseConfig::SharedPostgres { .. } => {
            envs.push(format!("POSTGRES_HOST=${{{}{}}}", var_prefix, "_POSTGRES_HOST"));
            envs.push(format!("POSTGRES_PORT=${{{}{}}}", var_prefix, "_POSTGRES_PORT"));
            envs.push(format!("POSTGRES_USER=${{{}{}}}", var_prefix, "_POSTGRES_USER"));
            envs.push(format!(
                "POSTGRES_PASSWORD=${{{}{}}}",
                var_prefix, "_POSTGRES_PASSWORD"
            ));
            envs.push(format!("POSTGRES_DB=${{{}{}}}", var_prefix, "_POSTGRES_DB"));
        }
        DatabaseConfig::None => {}
    }

    // 用户自定义环境变量
    for key in svc.env_vars.keys() {
        envs.push(format!("{}=${{{}_{}}}", key, var_prefix, key));
    }

    if envs.is_empty() {
        None
    } else {
        Some(envs)
    }
}

/// 构建健康检查配置（自动识别数据库镜像）
fn build_healthcheck(svc: &Service) -> Option<ComposeHealthCheck> {
    // 数据库容器自动配置健康检查
    let image_lower = svc.image.to_lowercase();

    if image_lower.contains("postgres") || image_lower.contains("postgis") {
        return Some(ComposeHealthCheck {
            test: Some(vec![
                "CMD-SHELL".to_string(),
                "pg_isready -U $${POSTGRES_USER:-admin}".to_string(),
            ]),
            interval: Some("10s".to_string()),
            timeout: Some("5s".to_string()),
            retries: Some(3),
            start_period: Some("30s".to_string()),
        });
    }

    if image_lower.contains("mysql") || image_lower.contains("mariadb") {
        return Some(ComposeHealthCheck {
            test: Some(vec![
                "CMD".to_string(),
                "mysqladmin".to_string(),
                "ping".to_string(),
                "-h".to_string(),
                "localhost".to_string(),
            ]),
            interval: Some("10s".to_string()),
            timeout: Some("5s".to_string()),
            retries: Some(3),
            start_period: Some("30s".to_string()),
        });
    }

    if image_lower.contains("redis") {
        return Some(ComposeHealthCheck {
            test: Some(vec![
                "CMD".to_string(),
                "redis-cli".to_string(),
                "ping".to_string(),
            ]),
            interval: Some("10s".to_string()),
            timeout: Some("5s".to_string()),
            retries: Some(3),
            start_period: Some("10s".to_string()),
        });
    }

    if image_lower.contains("nginx") {
        return Some(ComposeHealthCheck {
            test: Some(vec![
                "CMD-SHELL".to_string(),
                "wget -q -O /dev/null http://localhost:80/ || exit 1".to_string(),
            ]),
            interval: Some("10s".to_string()),
            timeout: Some("5s".to_string()),
            retries: Some(3),
            start_period: Some("10s".to_string()),
        });
    }

    None
}
